spring.application.name=artere
spring.datasource.url=jdbc:postgresql://localhost:5432/artere
spring.datasource.hikari.username=postgres
spring.datasource.hikari.password=postgres
spring.jpa.open-in-view=false

server.servlet.context-path=/v1/api

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always